version: '3'
services:
  static-server:
    #image: davyinsa/cloudrup-static-server
    build: . 
    container_name: static-server
    hostname: cloudrup-static-server.docker
    restart: always
    environment: 
      - APACHE_MAX_THREAD=100
    volumes:
      - ./aegir:/var/aegir
      - /var/log/apache2:/var/log/apache2
    ports:
      - "80:80"
      - "8022:22"
