#!/usr/bin/with-contenv bash
mkdir /var/log/aegir
mkdir -p /var/aegir/config
echo "" > /var/aegir/config/apache.conf
ln -sf /var/aegir/config/apache.conf /etc/apache2/conf-available/aegir.conf
ln -sf /etc/apache2/conf-available/aegir.conf /etc/apache2/conf-enabled/aegir.conf

exec apachectl -D FOREGROUND
