#!/usr/bin/with-contenv bash

PROCESS_NAME="apache"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting apache"
silent exec s6-setuidgid www-data apachectl -D FOREGROUND
