#!/usr/bin/with-contenv bash
#https://github.com/jmaciasportela/alpine-s6-nginx-php7-mysql-ssh/blob/master/rootfs/etc/services.d/ssh/run
set -e

mkdir -p /var/aegir/.ssh 
echo "" > /var/aegir/.ssh/authorized_keys 
chown aegir:aegir /var/aegir/.ssh/authorized_keys

# Copy default config from cache
if [ ! "$(ls -A /etc/ssh)" ]; then
   cp -a /etc/ssh.cache/* /etc/ssh/
fi

# Generate Host keys, if required
if ! ls /etc/ssh/ssh_host_* 1> /dev/null 2>&1; then
    ssh-keygen -A
fi

# Fix permissions, if writable
if [ -w ~/.ssh ]; then
    chown root:root ~/.ssh && chmod 700 ~/.ssh/
fi
if [ -w ~/.ssh/authorized_keys ]; then
    chown root:root ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys
fi

# Warn if no config
if [ ! -e /var/aegir/.ssh/authorized_keys ]; then
  echo "WARNING: No SSH authorized_keys found for aegir"
fi

mkdir /run/sshd
exec /usr/sbin/sshd -f /etc/ssh/sshd_config -D
