#!/usr/bin/with-contenv bash
#https://github.com/jmaciasportela/alpine-s6-nginx-php7-mysql-ssh/blob/master/rootfs/etc/services.d/ssh/run
set -e
if [ ! -d /var/aegir/.ssh ]; then
    mkdir -p /var/aegir/.ssh 
fi 

if [ ! -f /var/aegir/.ssh/authorized_keys ]; then
    echo "" > /var/aegir/.ssh/authorized_keys
    chown aegir:aegir /var/aegir/.ssh/authorized_keys
fi

# Warn if no config
if [ ! -e /var/aegir/.ssh/authorized_keys ]; then
    echo "WARNING: No SSH authorized_keys found for aegir"
fi

if [ ! -d /run/sshd ]; then
    mkdir /run/sshd
fi

echo "starting sshd..."

exec /usr/sbin/sshd -f /etc/ssh/sshd_config -D
